### ISSUE TITLE
What is format of TZ in env

### ISSUE THREAD

**Issue by enieber** [LibreCodeCoop/nextcloud-docker#13]
Hi, I am starting config the NextCloud with docker in my server and I have one question.

What is format TZ in env?

is number format like: `TZ=-3`
is string format like: `TZ=America/Sao_Paulo`
or is another format

**Comment by vitormattos** [comment]
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by vitormattos** [comment]
https://github.com/LibreCodeCoop/nextcloud-docker/pull/14
