### ISSUE TITLE
NEXTCLOUD_TRUSTED_DOMAINS where to add

### ISSUE THREAD

**Issue by hermesonfg** [LibreCodeCoop/nextcloud-docker#7]
I have follow all the steps and it work nicely, however, only outsite my network, coz I built it on my local server as VM. I have NOIP domains, and also a nextcloud running it but not as docker and the performance is not the same. So I wonder where I can set the "NEXTCLOUD_TRUSTED_DOMAINS" to make it visible inside my local network as I only set the VIRTUAL_HOST... thanks

**Comment by nerdseverino** [comment]
You need add this on config/config.php
